[package]
name = "file_randomizer"
version = "0.0.1"
edition = "2021"
authors = ["Stephen Kelzer"]

[dependencies]
clap = { version = "3.2.21", features = ["derive"] }
uuid = { version = "1.1.2", features = ["v4"] }
